[workspace]
members = [
    "00valentino",
    "demos/flagtester", "demos/platformer", "demos/cplatformer",
    "subpax/flag","subpax/cubeline","subpax/jellybean","subpax/pixie",
    "rider_mods/droqspawnables",
]
resolver = "2"

[workspace.package]
rust-version = "1.70.0"
version = "0.3.0"

[workspace.dependencies]
ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", branch = "main" }