[[pipelines]]
type = "Materials"
output_decals = false
[pipelines.importer]
type = "Single"
name = "brick10"
base_color = "brick10.png"

[[pipelines]]
type = "Materials"
output_decals = false
[pipelines.importer]
type = "Single"
name = "pL10"
base_color = "pL10.png"

[[pipelines]]
type = "Materials"
output_decals = false
[pipelines.importer]
type = "Single"
name = "pLUp10"
base_color = "pLUp10.png"

[[pipelines]]
type = "Materials"
output_decals = false
[pipelines.importer]
type = "Single"
name = "pR10"
base_color = "pR10.png"

[[pipelines]]
type = "Materials"
output_decals = false
[pipelines.importer]
type = "Single"
name = "pRUp10"
base_color = "pRUp10.png"